### ISSUE TITLE
 Failed to login

### ISSUE THREAD

**Issue by hugoohd97** [DonAurelio/SIGIA#1]
Django 1.8 and python 2.7 
It gives an error when wanting to log in to the system the error says (The view app.inicio.views.Login didn't return an HttpResponse object. It returned none instead)

**Comment by DonAurelio** [comment]
Hola hugoohd97, 

Podrías mostrar el stacktrace por favor

**Comment by hugoohd97** [comment]
![Sigia](https://user-images.githubusercontent.com/50031082/75908499-047a1080-5e29-11ea-9028-b52b06c23163.png)
![Sigia](https://user-images.githubusercontent.com/50031082/75908780-8f5b0b00-5e29-11ea-97d0-144f850d2cef.png)


I do not understand what you mean with stacktrace but I spend some screenshots when you are in the login and then when you want to enter

**Comment by DonAurelio** [comment]
Click on the 'Switch to copy-and-paste view' here 

![image](https://user-images.githubusercontent.com/9855594/75920237-f3cb9980-5e2c-11ea-96fa-5b8b5f386516.png)

And paste the traceback, the traceback is a log wich tell us about the functions that were called before the error was taken place.

**Comment by hugoohd97** [comment]
Environment:


Request Method: POST
Request URL: http://localhost:8000/inicio/login/

Django Version: 1.8
Python Version: 2.7.13
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'imagekit',
 'bootstrap3',
 'django.contrib.humanize',
 'easy_pdf',
 'apps.inicio',
 'apps.cuenta',
 'apps.empleado',
 'apps.sucursal',
 'apps.vehiculo',
 'apps.repuesto',
 'apps.cliente',
 'apps.orden_de_trabajo',
 'apps.cotizacion_orden_de_trabajo',
 'apps.factura_orden_de_trabajo',
 'apps.venta',
 'apps.cotizacion',
 'apps.proveedor',
 'apps.reporte',
 'apps.movil',
 'corsheaders')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'corsheaders.middleware.CorsMiddleware')


Traceback:
File "C:\Users\user\Desktop\Facultad\sigiaenv\lib\site-packages\django\core\handlers\base.py" in get_response
  151.                                  % (callback.__module__, view_name))

Exception Type: ValueError at /inicio/login/
Exception Value: The view apps.inicio.views.Login didn't return an HttpResponse object. It returned None instead.

**Comment by DonAurelio** [comment]
@hugoohd97 please check your code for indentation errors or something similar. I reviewed the code and I don't have insights regarding the code failure.

**Comment by hugoohd97** [comment]
The only thing that changed the code is the settings.py file to use a local database with pgAdmin, then the code is in the same state in which it is in the github


What version of python do you use? I use 2.7 but it would be better if I use one identical to yours

![Sin título](https://user-images.githubusercontent.com/50031082/76105551-e68ce700-5fb3-11ea-94aa-63077f434d18.png)
